# 🐳 Docker Compose for Local Development

# 🔧 Variables (only multi-use)
x-common-variables: &common-variables
  MINIO_USER: &minio_user "devuser"
  MINIO_PASSWORD: &minio_password "devpassword123"

services:

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: image-storage-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=*minio_user
      - MINIO_ROOT_PASSWORD=*minio_password
      - MINIO_REGION_NAME=eu-central-1
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # MinIO Client for bucket initialization
  minio-init:
    image: minio/mc:latest
    container_name: image-storage-minio-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-minio.sh:/init-minio.sh
    entrypoint: [ "/bin/sh", "/init-minio.sh" ]

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: image-storage-keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Waiting for database to be ready..."
        sleep 10
        echo "Starting Keycloak with realm import..."
        exec /opt/keycloak/bin/kc.sh start-dev --import-realm
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/8080' || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: image-storage-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgresSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: image-storage-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ImageStorage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ImageStorage" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Application
  image-storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-storage-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,keycloak
      - AWS_ACCESS_KEY_ID=*minio_user
      - AWS_SECRET_ACCESS_KEY=*minio_password
      - AWS_REGION=eu-central-1
      - AWS_S3_ENDPOINT=http://minio:9000
      - IMAGE_BUCKET_NAME=dev-images-bucket
      - THUMBNAIL_BUCKET_NAME=dev-thumbnails-bucket
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ImageStorage
      - SPRING_DATASOURCE_USERNAME=isUser
      - SPRING_DATASOURCE_PASSWORD=isPassword
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - KEYCLOAK_CLIENT_ID=image-storage-app
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/image-storage
      - KEYCLOAK_AUTH_URI=http://localhost:8081/realms/image-storage/protocol/openid-connect/auth
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/image-storage/protocol/openid-connect/token
      - KEYCLOAK_USERINFO_URI=http://keycloak:8080/realms/image-storage/protocol/openid-connect/userinfo
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/image-storage/protocol/openid-connect/certs
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  minio-data:
  postgres-data:
