spring:
  # PostgresSQL configuration for dev profile
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ImageStorage}
    username: ${SPRING_DATASOURCE_USERNAME:isUser}
    password: ${SPRING_DATASOURCE_PASSWORD:isPassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      # Enable JPA auditing
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

# Image configuration
image:
  bucket-name: ${IMAGE_BUCKET_NAME:images-bucket-dev}
  thumbnail-bucket-name: ${THUMBNAIL_BUCKET_NAME:thumbnails-bucket-dev}
  kms-key-id: ${KMS_KEY_ID:alias/aws/s3}
  cloudfront-domain: ${CLOUDFRONT_DOMAIN:}
  max-file-size: ${MAX_FILE_SIZE:10485760}
  region: ${AWS_REGION:eu-central-1}
  url-expiration-minutes: ${URL_EXPIRATION_MINUTES:15}
  thumbnail-sizes: [ 150, 300, 600 ]
  supported-types:
    - image/jpeg
    - image/png
    - image/webp
  max-results: ${MAX_RESULTS:1000}
  key-prefix: ${KEY_PREFIX:images}
