spring:
  # PostgresSQL configuration for dev profile
  datasource:
    url: jdbc:postgresql://localhost:5432/s3playground
    username: s3user
    password: s3password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      # Enable JPA auditing
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
