# Development Configuration

spring:
  # PostgresSQL configuration for dev profile
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ImageStorage}
    username: ${SPRING_DATASOURCE_USERNAME:isUser}
    password: ${SPRING_DATASOURCE_PASSWORD:isPassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false  # Allow clean in dev

  data:
    redis:
      host: localhost
      port: 6379

  # Keycloak for dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:image-storage-app}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/image-storage}
            authorization-uri: ${KEYCLOAK_AUTH_URI:http://localhost:8081/realms/image-storage/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8081/realms/image-storage/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:http://localhost:8081/realms/image-storage/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8081/realms/image-storage/protocol/openid-connect/certs}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/image-storage}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8081/realms/image-storage/protocol/openid-connect/certs}

# AWS configuration for local development
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:devuser}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:devpassword123}
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}

# Image configuration for dev
image:
  bucket-name: ${IMAGE_BUCKET_NAME:dev-images-bucket}
  thumbnail-bucket-name: ${THUMBNAIL_BUCKET_NAME:dev-thumbnails-bucket}
  kms-key-id: ${KMS_KEY_ID:alias/aws/s3}
  cloudfront-domain: ${CLOUDFRONT_DOMAIN:}
  max-file-size: ${MAX_FILE_SIZE:10485760}
  region: ${AWS_REGION:eu-central-1}
  url-expiration-minutes: ${URL_EXPIRATION_MINUTES:15}
  thumbnail-sizes: [ 150, 300, 600 ]
  supported-types:
    - image/jpeg
    - image/png
    - image/webp
  max-results: ${MAX_RESULTS:1000}
  key-prefix: ${KEY_PREFIX:images}
