apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: image-storage-pdb
  namespace: image-storage
  labels:
    app: image-storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: image-storage
      component: backend
