apiVersion: v1
kind: Service
metadata:
  name: image-storage-nodeport
  namespace: image-storage
  labels:
    app: image-storage
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: image-storage
