apiVersion: v1
kind: Service
metadata:
  name: image-storage-service
  namespace: image-storage
  labels:
    app: image-storage
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: image-storage
    component: backend
  sessionAffinity: None
